### ISSUE TITLE
Not show rewardedVideo with Animate cc 2018

### ISSUE THREAD

**Issue by nguyennguf** [myflashlab/Admob-ANE#51]
I am using latest version of the ANE.
When trying to publish it on real device, not show  rewardedVideo

```actionscript
package {

	import flash.display.MovieClip;
	import flash.events.MouseEvent;
	import flash.events.Event;
	import com.myflashlab.air.extensions.admob.*;
	import com.myflashlab.air.extensions.dependency.OverrideAir;



	public class AdMobExample extends MovieClip {
		public var mcClick: MovieClip;
		public var mcTxt: MovieClip;
		private var adRequest: AdRequest;
		public function AdMobExample() {

			if (!stage) {
				this.addEventListener(Event.ADDED_TO_STAGE, initialize);
			} else {
				initialize();
			}




		}
		private function initialize(event: Event = null): void {
			
			AdMob.init(stage, "ca-app-pub-8926120832374746~7829221157");
			adRequest = new AdRequest();
			AdMob.api.addEventListener(AdMobEvents.AD_LOADED, onAdLoaded);
			AdMob.api.rewardedVideo.loadAd(adRequest, "ca-app-pub-8926120832374746/3060589131");

		}

		private function onAdLoaded(e: AdMobEvents): void {
				
			if (e.adType == AdMob.AD_TYPE_REWARDED_VIDEO) {
				// Your Ad is ready to be shown. show it whenever you like!
				if (AdMob.api.rewardedVideo.isReady) {
					AdMob.api.rewardedVideo.show();
				}
			}
		}

		private function onDeliverReward(e: AdMobEvents): void {
			trace("onDeliverReward Type: " + e.rewardType + " amount: " + e.rewardAmount);
		}


	}

}
```
![2018-11-14_142424](https://user-images.githubusercontent.com/26294980/48466647-09244b00-e819-11e8-92fb-9a1922ca7a96.png)

**Comment by nguyennguf** [comment]
@myflashlab help me

**Comment by myflashlab** [comment]
it seems like you are trying to run this on Android. Well, please take your time and make sure you have read the sample project available in our GitHub. there you can see what your setup misses. To name one I noticed quickly is that you are missing the dependency ANEs! check this out: https://github.com/myflashlab/Admob-ANE#air-xml-manifest

**Comment by myflashlab** [comment]
All dependency ANEs are freely available in our [GitHub Repository](https://github.com/myflashlab/common-dependencies-ANE). And the link is shown on the sample project and sample codes. https://github.com/myflashlab/Admob-ANE/blob/master/AIR/Main-app.xml#L119

I'm posting the above link to help you in trying to compare your project with the sample project so you can make sure you have set everything correctly. Because I am seeing another error in your manifest! You should have ```<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />``` in your manifest but instead you have a String value for that! PLEASE take your time and read the documents fully and compare your setup with our sample project. That will save you a lot of time. 

However, We'd be happy to answer your questions as fast as we can.
